spring:
  server:
    port: 9090

  profiles:
    active: development

#  datasource:
#    url: jdbc:mysql://demodbfinal.ccdwitjkt0qb.eu-north-1.rds.amazonaws.com:3306/
#    username: admin
#    password: admin1234
#
#    jpa:
#      database-platform: org.hibernate.dialect.MySQL5Dialect
#
#    ddl-auto: update

#/spring-rds?useSSL=false